config/routes.rb
Tdgs::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :commodities

  resources :types

  resources :categories

  resources :re_ins

  resources :ingredients

  resources :me_res

  resources :recipes

  resources :meals

  resources :meetings
  
  
  
  
  mount Ckeditor::Engine => '/ckeditor'

    root :to => 'meetings#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipe
end

app/models/commodity.rb
class Commodity < ActiveRecord::Base
  has_many :recipe
end

app/models/dish.rb
class Dish < ActiveRecord::Base
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :re_ins
  has_many :recipes, through: :re_ins
end

app/models/me_re.rb
class MeRe < ActiveRecord::Base
  belongs_to :meal
  belongs_to :recipe
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  has_many :me_res
  has_many :recipes, through: :me_res
  belongs_to :meeting
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_many :meals
end

app/models/re_in.rb
class ReIn < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
  attr_accessor :ingredient_name
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :me_res
  has_many :meals, through: :me_res
  has_many :re_ins
  has_many :ingredients, through: :re_ins
  belongs_to :category
  belongs_to :type
  belongs_to :commodity
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    
  has_secure_password
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
    
  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :signed_in_user, only: [:index, :show, :edit, :update]
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all.order('meet_date DESC')
  end

  def new
    @meeting = Meeting.new
  end
  
  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  def edit
  end
  
  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meating was successfully created.' }
        format.json { render action: 'show', status: :created, location: @meeting }
      else
        format.html { render action: 'new' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /meeting/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :meet_date, :img_1)
    end
    
    # Before filters
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Logg inn."
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/me_res_helper.rb
module MeResHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/mettings_helper.rb
module MettingsHelper
end

app/helpers/re_ins_helper.rb
module ReInsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
  
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Tittel' %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
	  <%= f.label :meet_date, 'Møtedato' %><br/>
	  <%= f.date_field :meet_date %>
	</div>
	<div class="field">
		<%= f.label :img_1, 'Bilde'%><br/>
		<%= f.text_field :img_1 %>
	  <br/>
  <div class="actions">
    <%= f.submit "Registrer" %>
  </div>
<% end %>

app/views/meetings/_meal.html.erb
<p><strong><%= link_to meal.title, meal %></strong><br/>
<%= meal.ingress %></p>
<p>***</p>

app/views/meetings/edit.html.erb
<h1><%= @meeting.name %></h1>
<%= render 'form' %>

app/views/meetings/index.html.erb
<ol class="breadcrumb">
    <li><a href="/">Hjem</a></li>
</ol>
<div class="row">
    <div class="col-sm-10"><h1>Møter</h1></div>
    <div class="col-sm-2">
        <%= link_to 'Nytt møte', new_meeting_path, :class => "btn btn-default btn-xs", :method => :get  %>
    </div>
</div>

<div class="row">
<% @meetings.each do |meeting| %>
        <div class="col-sm-4 col-md-3">
            <div class="thumbnail">
	            <% if meeting.img_1 != '' %>
                     <%= link_to image_tag(meeting.img_1), meeting %><br/>
                <% else %>
                    <%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/tdgs/images/defaultFood.jpg'), meeting %><br/>
                <% end %>

	            <h4><%= link_to meeting.name, meeting %></h4>
	            <%= meeting.meet_date.strftime("%d.%m.%Y") %>
            </div>
        </div>
<% end %>

</div>
  

app/views/meetings/new.html.erb
<h1>Nytt møte</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<ol class="breadcrumb">
    <li><a href="/">Hjem</a></li>
    <li><%= @meeting.name%></li>
</ol>
    <div class="row">
		<div class="col-md-10 column" align="middle">
			<%= image_tag "kulinarisk_small.png" %>
        </div>
        <div class="col-md-2">
            <p><%= link_to "Legg til rett", new_meal_path, :id => "new-meal-btn",
                          :class => "btn btn-default btn-xs", :method => :get %></p>
            <p><%= link_to "Endre", edit_meeting_path(@meeting), :id => "edit-meal-btn", :class => "btn btn-default btn-xs", :method => :get %></p>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-md-10 column" align="middle">
			<h2>
				<%= @meeting.name %>
			</h2>
			<p>
				Møtedato: <%= @meeting.meet_date.strftime("%d.%m.%Y") %>
			</p>
			<h3>Meny</h3>
			<p>
				<%= render partial: 'meal', collection: @meeting.meals.order('sort_order ASC') %>
			</p>
		</div>
	</div>