config/routes.rb
Tdgs::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  resources :commodities

  resources :types

  resources :categories

  resources :re_ins

  resources :ingredients

  resources :me_res

  resources :recipes

  resources :meals

  resources :meetings
  
  
  
  
  mount Ckeditor::Engine => '/ckeditor'

    root :to => 'meetings#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipe
end

app/models/commodity.rb
class Commodity < ActiveRecord::Base
  has_many :recipe
end

app/models/dish.rb
class Dish < ActiveRecord::Base
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :re_ins
  has_many :recipes, through: :re_ins
end

app/models/me_re.rb
class MeRe < ActiveRecord::Base
  belongs_to :meal
  belongs_to :recipe
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  has_many :me_res
  has_many :recipes, through: :me_res
  belongs_to :meeting
end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  has_many :meals
end

app/models/re_in.rb
class ReIn < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
  attr_accessor :ingredient_name
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :me_res
  has_many :meals, through: :me_res
  has_many :re_ins
  has_many :ingredients, through: :re_ins
  belongs_to :category
  belongs_to :type
  belongs_to :commodity
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :recipe
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    
  has_secure_password
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
    
  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end
end

app/controllers/re_ins_controller.rb
class ReInsController < ApplicationController
  before_action :signed_in_user, only: [:index, :show, :edit, :update]
  before_action :set_re_in, only: [:show, :edit, :update, :destroy]

  # GET /re_ins
  def index
    @re_ins = ReIn.all
  end

  # GET /re_ins/1
  def show
  end

  # GET /re_ins/new
  def new
    @re_in = ReIn.new
  end

  # GET /re_ins/1/edit
  def edit
  end

  # POST /re_ins
  def create    
    ingredient_name = re_in_params[:ingredient_name].downcase
    @ingredient = Ingredient.find_by_name(ingredient_name)
    if !@ingredient      
      @ingredient = Ingredient.new({"name"=>ingredient_name})
      @ingredient.save
    end
    
    #@re_in = ReIn.new(re_in_params)
    @re_in = ReIn.new({"recipe_id"=>re_in_params[:recipe_id], "ingredient_id"=>@ingredient.id, "amount"=>re_in_params[:amount],
       "unit"=>re_in_params[:unit]})

    if @re_in.save
      respond_to do |format|
        format.js
      end      
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /re_ins/1
  def update
    if @re_in.update(re_in_params)
      redirect_to @re_in, notice: 'Re in was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /re_ins/1
  def destroy
    @re_in.destroy
    redirect_to re_ins_url, notice: 'Re in was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_re_in
      @re_in = ReIn.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def re_in_params
      params.require(:re_in).permit(:recipe_id, :ingredient_name, :ingredient_id, :amount, :unit)
    end
    
    # Before filters
    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Logg inn."
      end
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
  def textile(text)
    RedCloth.new(html_escape(text)).to_html
  end
  
  # Returns the full title on a per-page basis.
    def full_title(page_title)
      base_title = "Tromsø Dannede Gourmet Selskab"
      if page_title.empty?
        base_title
      else
        "#{base_title} | #{page_title}"
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/me_res_helper.rb
module MeResHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/mettings_helper.rb
module MettingsHelper
end

app/helpers/re_ins_helper.rb
module ReInsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
  
  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/re_ins/_form.html.erb
<script type="text/javascript">
    jQuery(function($) {
        $("#submit_ingredient_btn").submitIngredient();
    })

</script>


<%= form_for(@re_in) do |f| %>
  <% if @re_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@re_in.errors.count, "error") %> prohibited this re_in from being saved:</h2>

      <ul>
      <% @re_in.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="rein_ingredients">
	<% @recipe.re_ins.each do |rein| %>
        <li>  <%= rein.amount %> <%=rein.unit%> <%= rein.ingredient.name %> <%= link_to rein, method: :delete, data: { confirm: "Er du sikker?" } do %><span class="glyphicon glyphicon-trash"></span><%end%></li>
	<% end %>
</div>
<br/>
  <%= f.number_field :recipe_id, value:@recipe.id, hidden:true %>
        <table class="table-condensed">
            <tr>
		        <td><%= f.label :amount %></td>
		        <td><%= f.number_field :amount %></td>
            </tr>
            <tr>
                <td><%= f.label :unit, :class => "col-md-2-column" %></td>
                <td><%= f.text_field :unit, :class => "col-md-2-column" %></td>
            </tr>
            <tr>
                <td><%= f.label :ingredient_id %></td>
                <td><%= f.text_field :ingredient_name %></td>
            </tr>
        </table>

	<%= f.button "legg til", name: "submit_ingredient_btn", id: "submit_ingredient_btn", type: "button", class: "btn btn-large btn-primary" %>
<% end %>

app/views/re_ins/create.js.erb
jQuery(function($) {
    var itemval = '';
    <% rein = @re_in %>
	itemval += '<li><%=rein.amount%> <%=rein.unit%> <%=rein.ingredient.name%></li>'
    $("#rein_ingredients").append(itemval);
	
})

app/views/re_ins/edit.html.erb
<h1>Editing re_in</h1>

<%= render 'form' %>

<%= link_to 'Show', @re_in %> |
<%= link_to 'Back', re_ins_path %>

app/views/re_ins/index.html.erb
<h1>Listing re_ins</h1>

<table>
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Ingredient</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @re_ins.each do |re_in| %>
      <tr>
        <td><%= re_in.recipe_id %></td>
        <td><%= re_in.ingredient_id %></td>
        <td><%= link_to 'Show', re_in %></td>
        <td><%= link_to 'Edit', edit_re_in_path(re_in) %></td>
        <td><%= link_to 'Destroy', re_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Re in', new_re_in_path %>

app/views/re_ins/new.html.erb
<h1>New re_in</h1>

<%= render 'form' %>

<%= link_to 'Back', re_ins_path %>

app/views/re_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recipe:</strong>
  <%= @re_in.recipe.title %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%
  	if @re_ins.unit > 1 && re_in.ingredient.plural
		name = ingredient.plural
	else
		name = ingredient.name
	end
  %>
  <%= @re_in.amount %> <%=@re_in.unit%> <%= name %>
</p>



<%= link_to 'Edit', edit_re_in_path(@re_in) %> |
<%= link_to 'Back', re_ins_path %>